# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('floor', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('awaiting_order', 'Awaiting Order'), ('order_received', 'Order Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('awaiting_service', 'Awaiting Service'), ('served', 'Served'), ('awaiting_payment', 'Awaiting Payment'), ('reserved', 'Reserved'), ('attention', 'Attention Required'), ('offline', 'Offline')], db_index=True, default='available', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='restaurants.restaurant')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tables.table')),
            ],
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'status'], name='tables_tabl_restaur_715b06_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['restaurant', 'is_active'], name='tables_tabl_restaur_2e47cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('restaurant', 'number')},
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['restaurant', 'is_active'], name='tables_qrco_restaur_2c4c41_idx'),
        ),
    ]
