# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('new_order', 'New Order'), ('order_status', 'Order Status'), ('table_alert', 'Table Alert'), ('system', 'System')], default='system', max_length=30)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(blank=True, default='', max_length=200)),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_bn', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
