# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['restaurant', 'is_read'], name='notificatio_restaur_aede84_idx'),
        ),
    ]
