# Generated by Django 5.1.15 on 2026-08-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersession',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Client-generated UUID stored in localStorage to track per-device sessions.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='customersession',
            index=models.Index(fields=['table', 'device_id', 'is_active'], name='ordering_cu_table_i_299f95_idx'),
        ),
    ]
