# Generated by Django 5.1.15 on 2026-08-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_add_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dish_image',
            field=models.CharField(blank=True, default='', help_text='Snapshot of the dish image URL at order time.', max_length=500),
        ),
    ]
