# Generated by Django 5.1.15 on 2026-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_add_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Dine in'), ('take_away', 'Take away')], db_index=True, default='dine_in', max_length=20),
        ),
    ]
