# Generated by Django 5.1.15 on 2026-08-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_add_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='max_prep_time',
            field=models.PositiveIntegerField(default=30, help_text='Snapshot of max prep time in minutes.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='min_prep_time',
            field=models.PositiveIntegerField(default=15, help_text='Snapshot of min prep time in minutes.'),
        ),
    ]
