# Generated by Django 5.1.15 on 2026-09-24 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_dishmodifier_options_and_more'),
        ('ordering', '0007_repair_dish_image_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='modifier_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all modifier price_deltas at order time.', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_modifiers',
            field=models.JSONField(blank=True, default=list, help_text='[{"name": "Full", "group": "Size", "price_delta": "100.00"}, ...]'),
        ),
        migrations.CreateModel(
            name='CartItemModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_delta', models.DecimalField(decimal_places=2, help_text='Snapshot of modifier.price_delta at selection time.', max_digits=10)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_modifiers', to='ordering.cartitem')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.dishmodifier')),
            ],
            options={
                'indexes': [models.Index(fields=['cart_item'], name='ordering_ca_cart_it_7de2f2_idx')],
                'unique_together': {('cart_item', 'modifier')},
            },
        ),
    ]
