# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='')),
                ('address_line', models.CharField(blank=True, default='', max_length=255)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('upazila', models.CharField(blank=True, default='', max_length=120)),
                ('district', models.CharField(blank=True, default='', max_length=120)),
                ('division', models.CharField(blank=True, default='', max_length=120)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('bn', 'বাংলা')], default='en', max_length=5)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RestaurantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('invited_email', models.EmailField(blank=True, default='', max_length=254)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='restaurants.restaurant')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['slug'], name='restaurants_slug_d8b6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['status'], name='restaurants_status_6c4292_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmembership',
            index=models.Index(fields=['restaurant', 'user'], name='restaurants_restaur_8e3ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantmembership',
            index=models.Index(fields=['restaurant', 'is_active'], name='restaurants_restaur_953e5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantmembership',
            unique_together={('restaurant', 'user')},
        ),
    ]
