# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='menus.dish'),
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_modifiers', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='dishvariant',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menus.dish'),
        ),
        migrations.AddField(
            model_name='dishvariant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_variants', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menus.menu'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menus.menucategory'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['restaurant', 'is_active'], name='menus_menu_restaur_3fcc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'menu'], name='menus_menuc_restaur_fc2196_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'is_active'], name='menus_menuc_restaur_06a957_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['restaurant', 'category'], name='menus_dish_restaur_92c267_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['restaurant', 'is_available'], name='menus_dish_restaur_e87860_idx'),
        ),
    ]
