# Generated by Django 5.1.15 on 2026-08-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='max_prep_time',
            field=models.PositiveIntegerField(default=30, help_text='Maximum preparation time in minutes.'),
        ),
        migrations.AddField(
            model_name='dish',
            name='min_prep_time',
            field=models.PositiveIntegerField(default=15, help_text='Minimum preparation time in minutes.'),
        ),
    ]
