# Generated by Django 5.1.15 on 2026-09-24 04:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_add_prep_time'),
        ('restaurants', '0003_backfill_organizations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishmodifier',
            options={'ordering': ('display_order', 'name_en')},
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected when the customer opens this dish.'),
        ),
        migrations.CreateModel(
            name='DishAssociation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('support', models.PositiveIntegerField(default=0, help_text='Number of orders containing both dishes.')),
                ('confidence', models.DecimalField(decimal_places=3, default=0, help_text='P(dish_b | dish_a) = support / orders_with_a.', max_digits=5)),
                ('lift', models.DecimalField(decimal_places=2, default=1, help_text='confidence / P(dish_b). >1 = real association.', max_digits=6)),
                ('dish_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_as_a', to='menus.dish')),
                ('dish_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_as_b', to='menus.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_associations', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, default='', max_length=100)),
                ('min_selections', models.PositiveIntegerField(default=0, help_text='Minimum options the customer must select. 0 = optional, 1+ = required.')),
                ('max_selections', models.PositiveIntegerField(default=1, help_text='Maximum options the customer can select. 1 = radio, 2+ = checkboxes.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='menus.dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('display_order', 'name_en'),
            },
        ),
        migrations.AddField(
            model_name='dishmodifier',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional group this modifier belongs to. Null = standalone add-on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='menus.modifiergroup'),
        ),
        migrations.AddIndex(
            model_name='dishmodifier',
            index=models.Index(fields=['dish', 'group'], name='menus_dishm_dish_id_c4f9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='dishassociation',
            index=models.Index(fields=['restaurant', 'dish_a', '-confidence'], name='menus_disha_restaur_696c71_idx'),
        ),
        migrations.AddIndex(
            model_name='dishassociation',
            index=models.Index(fields=['restaurant', 'dish_b'], name='menus_disha_restaur_c0eeae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishassociation',
            unique_together={('restaurant', 'dish_a', 'dish_b')},
        ),
        migrations.AddIndex(
            model_name='modifiergroup',
            index=models.Index(fields=['dish', 'is_active'], name='menus_modif_dish_id_291b51_idx'),
        ),
    ]
