# Generated by Django 5.1.15 on 2026-08-15 01:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_bn', models.CharField(blank=True, default='', max_length=150)),
                ('description_en', models.TextField(blank=True, default='')),
                ('description_bn', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', help_text='Optional promo code customers can enter.', max_length=50)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 15 for 15%) or fixed BDT amount.', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order subtotal to qualify (0 = no minimum).', max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['restaurant', 'is_active'], name='billing_off_restaur_032e94_idx'), models.Index(fields=['restaurant', 'code'], name='billing_off_restaur_9b4450_idx')],
            },
        ),
    ]
