# Generated by Django 5.1.15 on 2026-08-15 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_offer_model'),
        ('menus', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='dish',
            field=models.ForeignKey(blank=True, help_text='Link to a specific dish to show offer price on that dish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='menus.dish'),
        ),
    ]
