"""Authentication API views."""

from __future__ import annotations

import logging

from django.contrib.auth import get_user_model
from apps.restaurants.models import Restaurant
from rest_framework import generics, permissions, serializers, status
from rest_framework.response import Response
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .serializers import (
    InviteClaimSerializer,
    RegisterSerializer,
    RestaurantTokenObtainPairSerializer,
)

logger = logging.getLogger(__name__)

User = get_user_model()


class RegisterView(generics.CreateAPIView):
    serializer_class = RegisterSerializer
    permission_classes = (permissions.AllowAny,)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()
        return Response(
            {"id": str(user.id), "email": user.email},
            status=status.HTTP_201_CREATED,
        )


class LoginView(TokenObtainPairView):
    serializer_class = RestaurantTokenObtainPairSerializer
    permission_classes = (permissions.AllowAny,)


class RefreshView(TokenRefreshView):
    permission_classes = (permissions.AllowAny,)


class InviteClaimView(generics.CreateAPIView):
    """Claim a staff invitation: set password + profile on a placeholder user.

    The token is a signed value (email + restaurant id) generated by the
    dashboard when inviting; signed with Django's SECRET_KEY so it cannot
    be forged.
    """

    permission_classes = (permissions.AllowAny,)
    serializer_class = InviteClaimSerializer

    def get(self, request, *args, **kwargs):
        """Pre-flight token check so the form can fail fast with context."""
        from django.core import signing

        token = request.query_params.get("token", "")
        try:
            data = signing.loads(token, max_age=60 * 60 * 24 * 7, salt="staff-invite")
            email = data["email"]
            restaurant = Restaurant.objects.filter(pk=data["restaurant"]).first()
            if restaurant is None:
                raise KeyError("restaurant")
        except Exception:
            logger.warning("Invite pre-flight rejected: bad token")
            return Response(
                {"valid": False, "detail": "This invitation link is invalid or has expired."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        return Response(
            {"valid": True, "email": email, "restaurant": restaurant.name},
            status=status.HTTP_200_OK,
        )

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if not serializer.is_valid():
            logger.warning(
                "Invite claim rejected: errors=%s", serializer.errors
            )
        serializer.is_valid(raise_exception=True)
        user, membership = serializer.save()
        logger.info(
            "Invite claimed: email=%s restaurant=%s", user.email, membership.restaurant_id
        )
        return Response(
            {
                "id": str(user.id),
                "email": user.email,
                "restaurant": membership.restaurant.name,
                "role": membership.role.name_en if membership.role else None,
            },
            status=status.HTTP_200_OK,
        )


class MeView(generics.RetrieveUpdateAPIView):
    """Retrieve or update the current authenticated user's profile."""

    class OutputSerializer(RegisterSerializer):
        avatar = serializers.ImageField(required=False, allow_null=True)
        # Password is optional on profile updates — only validate when provided.
        password = serializers.CharField(write_only=True, required=False, allow_blank=True, trim_whitespace=False)
        password_confirm = serializers.CharField(write_only=True, required=False, allow_blank=True, trim_whitespace=False)

        class Meta(RegisterSerializer.Meta):
            fields = ("id", "email", "full_name", "phone", "preferred_language", "avatar")
            read_only_fields = ("id", "email")

        def validate(self, attrs: dict[str, Any]) -> dict[str, Any]:
            # Delegate to parent — it already handles missing password gracefully.
            return super().validate(attrs)

        def validate_email(self, value: str) -> str:
            # Allow keeping the same email on profile update.
            if self.instance and self.instance.email.lower() == value.strip().lower():
                return value.strip().lower()
            return super().validate_email(value)

        def update(self, instance, validated_data):
            password = validated_data.pop("password", None)
            validated_data.pop("password_confirm", None)
            user = super().update(instance, validated_data)
            if password:
                user.set_password(password)
                user.save(update_fields=["password"])
            return user

    serializer_class = OutputSerializer

    def get_object(self):
        return self.request.user

    def perform_update(self, serializer):
        request = self.request
        files = {k: (v.name, v.size) for k, v in request.FILES.items()} if request.FILES else {}
        logger.info("MeView.perform_update: data_keys=%s files=%s", list(request.data.keys()), files)
        return serializer.save()
