# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=150)),
                ('name_bn', models.CharField(blank=True, default='', max_length=150)),
                ('group', models.CharField(db_index=True, default='general', max_length=60)),
            ],
            options={
                'ordering': ('group', 'codename'),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, default='', max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission')),
            ],
        ),
    ]
