# Generated by Django 5.1.15 on 2026-08-14 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Null for globally shared system roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['restaurant', 'slug'], name='rbac_role_restaur_fb8699_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('restaurant', 'slug')},
        ),
    ]
