# Generated by Django 5.1.15 on 2026-09-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menuembedding',
            new_name='chatbot_men_restaur_94300b_idx',
            old_name='chatbot_menu_rest_is_avail_idx',
        ),
    ]
